require 'pathname'

task :default => ["vim:update_plugins"] do
end

namespace :vim do

  task :ensure_bundle_dir do
    bundle_home = Pathname.new( ENV['HOME'] ) + '.vim' + 'bundle'
    mkdir_p bundle_home
  end

  task :update_plugins => [:ensure_bundle_dir] do
    vim_dir = Pathname.new( ENV['HOME'] ) + '.vim' 
    sh "vim -u #{vim_dir}/bundles.vim +PluginInstall +qall"
    sh "cd bundle/vimproc.vim && make"
  end

  task :bootstrap => [:install_vundle, :update_plugins] do
  end

  task :install_vundle => [:ensure_bundle_dir] do
    vim_dir = Pathname.new( ENV['HOME'] ) + '.vim' 
    bundle_home = vim_dir + 'bundle'
    sh "rm -rf #{bundle_home}/vundle"
    sh "rm -rf #{bundle_home}/Vundle.vim"
    sh "git clone http://github.com/gmarik/Vundle.vim.git #{bundle_home}/Vundle.vim"

  end # task :bundles

end # namespace :update
