require 'pathname'

task :default => ["vim:update"] do
end

namespace :vim do

  task :ensure_bundle_dir do
    bundle_home = Pathname.new( ENV['HOME'] ) + '.vim' + 'bundle'
    mkdir_p bundle_home
  end

  def vim_script(id)
    "http://www.vim.org/scripts/download_script.php?src_id=#{id}"
  end

  def github(project)
    "git://github.com/#{project}.git"
  end

  BUNDLES = {
    :bufexplorer   => vim_script(12904),
    :taglist       => vim_script(7701),
    :tvo           => vim_script(5768),
    
    :ack              => github("mileszs/ack.vim"),
    :nerdtree         => github("wycats/nerdtree"),
    :nerdcommenter    => github("scrooloose/nerdcommenter"),
    
    :gist             => github("vim-scripts/Gist.vim"),
    :surround         => github("tpope/vim-surround"),

    :syntax_git       => github("tpope/vim-git"),
    :syntax_markdown  => github("ujihisa/vim-markdown"),
    :syntax_puppet    => vim_script(8052),
    :syntax_textile   => github("timcharper/textile.vim")
  }

  desc "update any bundles defined in the Rakefile"
  task :update => [:ensure_bundle_dir] do

    bundle_home = Pathname.new( ENV['HOME'] ) + '.vim' + 'bundle'
    BUNDLES.sort_by {|k,v| k.to_s }.each do |bundle, location|
      target_path = bundle_home + bundle.to_s

      next if File.exists? target_path

      puts "*** Installing #{bundle} to #{target_path} from #{location}"

      if location =~ /git$/
        sh "git clone #{location} #{target_path} > /dev/null"
        rm_rf target_path + '.git'
      elsif location =~ /download_script/
        mkdir_p target_path
        if filename= `curl --silent --head #{location} | grep attachment`[/filename=(.+)/,1]
          filename.strip!
          case filename
          when /zip$/
            sh "curl -s '#{location}' > /tmp/#{filename}"
            sh "unzip -o /tmp/#{filename} -d #{target_path}"
          when /tar\.gz$/
            sh "cd #{target_path} && curl -s '#{location}' | tar zx -"
          end
        else
          raise ArgumentError, "unknown script type"
        end
      end

      docdir = target_path + 'doc'
      if docdir.exist?
        puts "doc dir exists; tagging"
        sh "vim -u NONE -esX -c 'helptags #{docdir}' -c quit"
      end

      puts # blank line
    end
  end # task :bundles

end # namespace :update

